baseURL: https://notaryproject.dev/
enableRobotsTxt: true

theme: [docsy]

# Will give values to .Lastmod etc.
enableGitInfo: true

# Language settings
contentDir: content/en
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
languageCode: en-us

# Useful when translating.
enableMissingTranslationPlaceholders: true

disableKinds: [taxonomy, term]

# Highlighting config
pygmentsCodeFences: true
pygmentsUseClasses: false
# Use the new Chroma Go highlighter in Hugo.
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle: fruity # "tango"

# Image processing configuration.
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: smart

languages:
  en:
    title: Notary | Signing and verifying artifacts. Safeguarding the software delivery security from development to deployment.
    description: >-
      The Notary project comprises a server and a client for running and
      interacting with trusted collections.
    languageName: English
    contentDir: content/en
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style: tango
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # guessSyntax: true

# Everything below this are Site Params

params:
  copyright: Notary Project Authors
  description: >-
    A distributed, reliable key-value store for the most critical data of a
    distributed system

    # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
  github_repo: https://github.com/notaryproject/notaryproject.dev
  github_branch: main

  # An optional link to a related project repo. For example, the sibling repository where your product code lives.
  github_project_repo: https://github.com/notaryproject/notaryproject

  # Enable Algolia DocSearch
  algolia_docsearch: false

  # Enable Lunr.js offline search
  offlineSearch: false

  # Enable syntax highlighting and copy buttons on code blocks with Prism
  prism_syntax_highlighting: true

  # Versions

  # Menu title if your navbar has a versions selector to access old versions of your site.
  # This menu appears only if you have at least one [params.versions] set.
  # version_menu: Versions
  # versions:
    # latest: v2
    # all:
      # - v2
      # - v1
    # deprecation_warning: |-
      # the documentation is no longer actively maintained.
      # The page that you are viewing is the last archived version.

  # User interface configuration
  ui:
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact: true

    #  Set to true to disable breadcrumb navigation.
    breadcrumb_disable: false

    #  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable: false

    #  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
    navbar_logo: true

    # Set to true to disable the About link in the site footer
    footer_about_disable: true

    # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
    # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
    # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
    # add "hide_feedback: true" to the page's front matter.
    feedback:
      enable: true
      # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
      'yes': >-
        Glad to hear it! Please <a
        href="https://github.com/notaryproject/notaryproject.dev/issues/new">tell us how we
        can improve</a>.
      'no': >-
        Sorry to hear that. Please <a
        href="https://github.com/notaryproject/notaryproject.dev/issues/new">tell us how we
        can improve</a>.

    # Adds a reading time to the top of each doc.
    # If you want this feature, but occasionally need to remove the Reading time from a single page,
    # add "hide_readingtime: true" to the page's front matter
    readingtime:
      enable: false

  # Navbar config
  navbar:
    logos:
      github:
        url: https://github.com/notaryproject/notaryproject
      twitter:
        url: https://mobile.twitter.com/NotaryProject
      slack:
        url: https://app.slack.com/client/T08PSQ7BQ/CQUH8U287/

  # Footer Links
  links:
    # End user relevant links. These will show up on left side of footer and in the community page if you have one.
    user:
      # - name: Google Group
      #   url: https://groups.google.com/forum/?hl=en#!forum/etcd-dev
      #   icon: fab fa-google
      # - name: Twitter
      #   url: https://twitter.com/etcdio
      #   icon: fab fa-twitter
      - name: Stack Overflow
        url: https://stackoverflow.com/questions/tagged/notary
        icon: fab fa-stack-overflow
    # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
    developer:
      - name: Notary Project on GitHub
        url: https://github.com/notaryproject/notaryproject
        icon: fab fa-github-square
      - name: notaryproject.dev on GitHub
        url: https://github.com/notaryproject/notaryproject.dev
        icon: fab fa-github
  # [params.logos]
  hero: >-
    https://github.com/cncf/artwork/raw/master/projects/notary/horizontal/black/notary-horizontal-black.png

mediaTypes:
  text/netlify: {}

outputFormats:
  REDIRECTS:
    mediaType: text/netlify
    baseName: _redirects
    notAlternative: true

outputs:
  home: [HTML, REDIRECTS, RSS]

# Site menu (partial -- also see pages with 'menu' in front matter)
menu:
  main:
    - name: Blog
      url: ./blog/
      weight: -50
    - name: Roadmap
      url: https://github.com/notaryproject/roadmap
      weight: -20
